"""AgentRuntime + AgentHandle SPI — the driver contract.

Runtime implementers fill in these two Protocols to plug their agent
platform (a Docker-hosted stack, OpenAI Assistants, etc.) into Wind Tunnel
scenarios without modifying a single scenario file.

Analogy: AgentRuntime is to Wind Tunnel what WebDriver is to Selenium —
the portability seam. The framework defines the contract; concrete
implementations (windtunnel.runtimes.*) satisfy it.

Hierarchy
---------
AgentRuntime.provision(config) -> AgentHandle
    Creates/wires a handle to a running agent for one test batch.
    Called once per batch; expensive operations (container start,
    SSH tunnel, model load) belong here.

AgentHandle
    Represents a live agent for the duration of the test batch.

    send(messages, session_id) -> Response
        Drive one turn. session_id is EXPLICIT — the caller threads
        the same id across turns in a multi-turn scenario. The SPI
        exposes the plumbing; scenario authors never see session ids.

    reset_state() -> None
        **Between scenarios** (cheap, frequent).
        Wipes per-session state so the next scenario starts clean.
        For the RawDockerRuntime this means wiping state.db's
        messages/sessions/FTS tables. Should complete in <1 second.
        Called before every scenario run (unless skip_reset=True).

    teardown() -> None
        **Between batches** (expensive, infrequent).
        Destroys the runtime resources (stop container, kill SSH tunnel,
        unload model). Called once when the batch is finished.
        Must not raise if called on an already-torn-down handle.

Design notes
------------
- Message and Response are plain dicts (OpenAI-wire-compatible) rather
  than typed dataclasses. This keeps the SPI flexible — runtimes that
  return extra fields don't break the framework.
- AgentConfig carries platform-agnostic knobs. Platform-specific config
  (SSH jump host, Docker network name, etc.) lives in the concrete
  runtime's __init__, not here.
- session_id is a str (UUID) generated by the caller for each scenario
  run. The SPI just threads it through; runtimes map it to whatever
  their platform uses (a session-id header, thread_id, etc.).
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Protocol, runtime_checkable

# ─── Data types ───────────────────────────────────────────────────────────────

Message = dict[str, Any]   # OpenAI wire shape: {"role": ..., "content": ...}
Response = dict[str, Any]  # flat message OR OpenAI choices response (see AgentHandle.send)


@dataclass
class ModelSpec:
    """Identifies which model/quantization to use.

    name:  model identifier (e.g. "llama-3.3-70b", "mistral-small-3.2-4bit")
    quant: quantization label for trace recording (e.g. "4bit", "8bit", "unknown")
    """
    name: str
    quant: str = "unknown"


@dataclass
class SamplingConfig:
    """Sampling knobs for one scenario run.

    All fields are optional — None means "use runtime default" (typically
    greedy for the RawDockerRuntime).

    temperature: float in [0.0, 2.0]. 0.0 = greedy.
    top_p:       float in (0.0, 1.0]. 1.0 = no nucleus pruning.
    tool_choice: "auto" | "none" | "required" | specific tool name.
    max_tokens:  hard token budget for this run.
    """
    temperature: float | None = None
    top_p: float | None = None
    tool_choice: str | None = None
    max_tokens: int | None = None


@dataclass
class MCPSpec:
    """Reference to one MCP server that the agent should use.

    name: the server alias the agent config knows (e.g. "acme").
    url:  the HTTP URL the agent runtime should point the agent at.
    """
    name: str
    url: str


@dataclass
class AgentConfig:
    """Platform-agnostic configuration for one agent under test.

    These are the knobs that describe WHAT agent to test, not HOW to
    run it. Platform-specific config (SSH host, Docker network, etc.)
    lives in the runtime's own __init__.

    system_prompt:  override for the agent's system prompt. None = use
                    the runtime's default / SOUL.md baseline.
    persona_doc:    path to the SOUL.md / persona file to inject.
                    None = use the runtime's default persona.
    skills:         list of skill file paths to make available to the
                    agent (e.g. SOUL.md-style .md files). Empty = default.
    mcp_servers:    list of MCPSpec references. The runtime maps each
                    MCPSpec to its platform's MCP config mechanism.
    model:          which model/quant to use. None = runtime default.
    sampling:       sampling config for this run. None = runtime default
                    (typically greedy).
    agent_id:       human-readable identifier recorded in the Trace.
    variant_id:     variant label recorded in the Trace (e.g. "prod_v5").
    """
    agent_id: str = "agent"
    variant_id: str = "default"
    system_prompt: str | None = None
    persona_doc: Path | None = None
    skills: list[Path] = field(default_factory=list)
    mcp_servers: list[MCPSpec] = field(default_factory=list)
    model: ModelSpec | None = None
    sampling: SamplingConfig | None = None


# ─── Protocols ────────────────────────────────────────────────────────────────

@runtime_checkable
class AgentHandle(Protocol):
    """Live handle to a running agent for one test batch.

    Implementers: RawDockerRuntime.AgentHandleImpl, InMemoryRuntime.AgentHandleImpl, etc.

    Contract:
    - send() may be called any number of times between reset_state() calls.
    - reset_state() must be idempotent (safe to call on a clean handle).
    - teardown() must be idempotent (safe to call multiple times / after a crash).
    - After teardown(), send() and reset_state() behaviour is undefined.
    """

    def send(self, messages: list[Message], session_id: str) -> Response:
        """Drive one turn through the agent.

        messages:   accumulated conversation history in OpenAI wire format.
                    For a single-turn scenario this is [{"role":"user","content":"..."}].
                    For multi-turn the caller appends prior assistant turns before
                    each call, threading the same session_id throughout.
        session_id: explicit UUID for this scenario run. Multi-turn scenarios
                    pass the SAME id on every call so the agent accumulates state.
                    Single-turn scenarios generate a fresh UUID per run.

        Returns a response dict in EITHER of two accepted shapes
        (the runner's _extract_reply normalizes both):

        - flat message — the forward-looking minimal contract:
            {"content": "...", "tool_calls": [...]}
          (also accepted wrapped: {"message": {"content": ..., "tool_calls": ...}})
        - OpenAI chat-completions — kept for OpenAI-compat, so a runtime
          can return an upstream completions payload untouched:
            {"choices": [{"message": {"role": "assistant", "content": "...",
                                      "tool_calls": [...]}}]}

        In both shapes "content" is the assistant's text (None/missing
        normalizes to "") and "tool_calls" is the list of tool calls in
        whatever wire shape the platform emits (recorded faithfully on
        the Trace; missing normalizes to []).
        """
        ...

    def reset_state(self) -> None:
        """Wipe per-session state between scenarios.

        Called before EACH scenario run (cheap, frequent — target <1s).
        Must leave the agent ready to start a fresh, uncontaminated scenario.

        For RawDockerRuntime: wipes state.db messages/sessions/FTS tables.
        For InMemoryRuntime: clears in-process conversation state.
        For a platform runtime (e.g. AcmeRuntime): clears the session on
        the platform backend.

        DISTINCT from teardown() — this is per-scenario cleanup, not
        per-batch teardown. Runtimes that conflate the two will cause
        cross-scenario contamination (e.g. answers served from a prior
        run's search index — see api/state_reset.py).
        """
        ...

    def teardown(self) -> None:
        """Destroy runtime resources at end of batch.

        Called once when all scenarios in the batch are done (expensive,
        infrequent). Stops containers, kills tunnels, unloads models.

        Must be idempotent — safe to call if already torn down or if
        provisioning failed partway through.
        """
        ...


@runtime_checkable
class AgentRuntime(Protocol):
    """Factory that provisions an AgentHandle for one test batch.

    Implementers: RawDockerRuntime, InMemoryRuntime, platform drivers
    (e.g. AcmeRuntime).

    provision() is called once per batch. It should perform all expensive
    setup (start container, open SSH tunnel, configure agent with the
    AgentConfig knobs) and return a handle ready for send() calls.

    The caller (run_scenario / run_matrix) is responsible for calling
    handle.teardown() when the batch is finished.
    """

    def provision(self, config: AgentConfig, mcps: list | None = None) -> AgentHandle:
        """Provision a live agent handle for the given config.

        May perform expensive operations: container start, SSH tunnel
        establishment, SOUL.md injection, model warmup, etc. Called
        once per batch.

        mcps: list of ALREADY-STARTED MCPHandle objects (started by the
            runner before calling provision). Runtimes that need to register
            upstream MCP servers (e.g. a platform runtime) use these handles'
            .url to perform registration. Runtimes that don't care about MCP
            registration (RawDockerRuntime, InMemoryRuntime) accept and ignore
            this parameter — their agent config points directly at the mcp url.

        Returns an AgentHandle ready to accept send() calls.
        Raises RuntimeError if provisioning fails (container won't start,
        SSH unreachable, etc.) — caller should propagate, not swallow.
        """
        ...
